### ISSUE TITLE
pluralsight.com: unable to run the repo (unhandled error event)

### ISSUE THREAD

**Issue by quintons** [danielstern/isomorphic-react#21]
I have tried to clone the master branch twice, installed an early version of node (did not work) with no luck. you suggested in the .md to upgrade the global version of webpack, but as I have a current live clients ecommerce site on the system I can not - besides it is bad practice to have a globally installed webpack.

The result after performing a 'start-dev' was the following:
➜  isomorphic-react git:(master) ✗ yarn run start-dev
yarn run v1.16.0
$ cross-env NODE_ENV=development babel-node server --useServerRender=true --useLiveData=false
Warning: Please use `require("history").createMemoryHistory` instead of `require("history/createMemoryHistory")`. Support for the latter will be removed in the next major release.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:3000
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at Server.setupListenHandle [as _listen2] (net.js:1322:14)
    at listenInCluster (net.js:1370:12)
    at doListen (net.js:1492:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at Object.<anonymous> (/MyFiles/development/jest/isomorphic-react/node_modules/@babel/node/lib/_babel-node.js:234:23)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  isomorphic-react git:(master) ✗ node -v
v8.4.0
➜  isomorphic-react git:(master) ✗ 

I copied it from the terminal. Can you please help on this as I have wasted so much time.
Thanks :)

**Comment by danielstern** [comment]
Hello, it sounds like you already have something running on `Port 3000`. Check your other applications.
