### ISSUE TITLE
Cannot find module 'babel-plugin-transform-object-rest-spread' from 

### ISSUE THREAD

**Issue by manishjain-hrbl** [danielstern/isomorphic-react#23]
Steps to reproduce run below:
```
git clone
git checkout jest
npm i
npm run test-dev
```

` FAIL  src/reducers/questions.spec.js
  ● Test suite failed to run

    Cannot find module 'babel-plugin-transform-object-rest-spread' from '/Users/manishjain/isomorphic-react'

      at Function.module.exports [as sync] (node_modules/resolve/lib/sync.js:69:15)
      at resolveStandardizedName (node_modules/@babel/core/lib/config/files/plugins.js:101:31)
      at resolvePlugin (node_modules/@babel/core/lib/config/files/plugins.js:54:10)
      at loadPlugin (node_modules/@babel/core/lib/config/files/plugins.js:62:20)
      at createDescriptor (node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
      at items.map (node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
          at Array.map (<anonymous>)
      at createDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
      at createPluginDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
      at plugins (node_modules/@babel/core/lib/config/config-descriptors.js:40:19)

 FAIL  src/components/__tests__/QuestionDetail.js
  ● Test suite failed to run

    Cannot find module 'babel-plugin-transform-object-rest-spread' from '/Users/manishjain/isomorphic-react'

      at Function.module.exports [as sync] (node_modules/resolve/lib/sync.js:69:15)
      at resolveStandardizedName (node_modules/@babel/core/lib/config/files/plugins.js:101:31)
      at resolvePlugin (node_modules/@babel/core/lib/config/files/plugins.js:54:10)
      at loadPlugin (node_modules/@babel/core/lib/config/files/plugins.js:62:20)
      at createDescriptor (node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
      at items.map (node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
          at Array.map (<anonymous>)
      at createDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
      at createPluginDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
      at plugins (node_modules/@babel/core/lib/config/config-descriptors.js:40:19)

 FAIL  src/components/QuestionList.spec.js
  ● Test suite failed to run

    Cannot find module 'babel-plugin-transform-object-rest-spread' from '/Users/manishjain/isomorphic-react'

      at Function.module.exports [as sync] (node_modules/resolve/lib/sync.js:69:15)
      at resolveStandardizedName (node_modules/@babel/core/lib/config/files/plugins.js:101:31)
      at resolvePlugin (node_modules/@babel/core/lib/config/files/plugins.js:54:10)
      at loadPlugin (node_modules/@babel/core/lib/config/files/plugins.js:62:20)
      at createDescriptor (node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
      at items.map (node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
          at Array.map (<anonymous>)
      at createDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
      at createPluginDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
      at plugins (node_modules/@babel/core/lib/config/config-descriptors.js:40:19)

 FAIL  src/sagas/fetch-question-saga.spec.js
  ● Test suite failed to run

    Cannot find module 'babel-plugin-transform-object-rest-spread' from '/Users/manishjain/isomorphic-react'

      at Function.module.exports [as sync] (node_modules/resolve/lib/sync.js:69:15)
      at resolveStandardizedName (node_modules/@babel/core/lib/config/files/plugins.js:101:31)
      at resolvePlugin (node_modules/@babel/core/lib/config/files/plugins.js:54:10)
      at loadPlugin (node_modules/@babel/core/lib/config/files/plugins.js:62:20)
      at createDescriptor (node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
      at items.map (node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
          at Array.map (<anonymous>)
      at createDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
      at createPluginDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
      at plugins (node_modules/@babel/core/lib/config/config-descriptors.js:40:19)

 FAIL  src/components/__tests__/NotificationsViewer.js
  ● Test suite failed to run

    Cannot find module 'babel-plugin-transform-object-rest-spread' from '/Users/manishjain/isomorphic-react'

      at Function.module.exports [as sync] (node_modules/resolve/lib/sync.js:69:15)
      at resolveStandardizedName (node_modules/@babel/core/lib/config/files/plugins.js:101:31)
      at resolvePlugin (node_modules/@babel/core/lib/config/files/plugins.js:54:10)
      at loadPlugin (node_modules/@babel/core/lib/config/files/plugins.js:62:20)
      at createDescriptor (node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
      at items.map (node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
          at Array.map (<anonymous>)
      at createDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
      at createPluginDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
      at plugins (node_modules/@babel/core/lib/config/config-descriptors.js:40:19)

 FAIL  src/App.spec.js
  ● Test suite failed to run

    Cannot find module 'babel-plugin-transform-object-rest-spread' from '/Users/manishjain/isomorphic-react'

      at Function.module.exports [as sync] (node_modules/resolve/lib/sync.js:69:15)
      at resolveStandardizedName (node_modules/@babel/core/lib/config/files/plugins.js:101:31)
      at resolvePlugin (node_modules/@babel/core/lib/config/files/plugins.js:54:10)
      at loadPlugin (node_modules/@babel/core/lib/config/files/plugins.js:62:20)
      at createDescriptor (node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
      at items.map (node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
          at Array.map (<anonymous>)
      at createDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
      at createPluginDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
      at plugins (node_modules/@babel/core/lib/config/config-descriptors.js:40:19)

 FAIL  src/components/TagsList.spec.js
  ● Test suite failed to run

    Cannot find module 'babel-plugin-transform-object-rest-spread' from '/Users/manishjain/isomorphic-react'

      at Function.module.exports [as sync] (node_modules/resolve/lib/sync.js:69:15)
      at resolveStandardizedName (node_modules/@babel/core/lib/config/files/plugins.js:101:31)
      at resolvePlugin (node_modules/@babel/core/lib/config/files/plugins.js:54:10)
      at loadPlugin (node_modules/@babel/core/lib/config/files/plugins.js:62:20)
      at createDescriptor (node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
      at items.map (node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
          at Array.map (<anonymous>)
      at createDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
      at createPluginDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:105:10)
      at plugins (node_modules/@babel/core/lib/config/config-descriptors.js:40:19)

Test Suites: 7 failed, 7 total
Tests:       0 total
Snapshots:   0 total
Time:        2.153s
Ran all test suites.

Watch Usage: Press w to show more.

`

**Comment by GaddMaster** [comment]
Not sure but try installing it no ?
