### ISSUE TITLE
Invariant failed: You should not use <Link> outside a <Router>

### ISSUE THREAD

**Issue by Karnadeep** [danielstern/isomorphic-react#67]
Error: Invariant failed: You should not use Link outside a Router
    at invariant (/Users/karnadeeprana/Documents/ReactWorkspace/isomorphic-react/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:13:11)
    at Object.children (/Users/karnadeeprana/Documents/ReactWorkspace/isomorphic-react/node_modules/react-router-dom/modules/Link.js:89:11)
    at ReactDOMServerRenderer.render (/Users/karnadeeprana/Documents/ReactWorkspace/isomorphic-react/node_modules/react-dom/cjs/react-dom-server.node.development.js:3635:55)
    at ReactDOMServerRenderer.read (/Users/karnadeeprana/Documents/ReactWorkspace/isomorphic-react/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/Users/karnadeeprana/Documents/ReactWorkspace/isomorphic-react/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at /Users/karnadeeprana/Documents/ReactWorkspace/isomorphic-react/server/index.jsx:88:29
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/karnadeeprana/Documents/ReactWorkspace/isomorphic-react/node_modules/co/index.js:65:19)

**Comment by Karnadeep** [comment]
Trying to fix above gives rise to the below issue
You should not use Route outside a Router
